accounts=["9c885ce7664ed3c3675df8e49590c141665d94add5bf72a816a8d8a78bd8fbe5"]
rpc="http://0.0.0.0:8888"

[api]
sms="https://zc.33.cn/api2/sms/send"
mail="https://zc.33.cn/api2/sms/mailsend"
walletInfo="http://47.74.9.155:45656/walletinfo"
transfer="http://47.74.9.155:57979/admintoinbank"

[receipts]
sms=[""] #短信通知用户列表
mail=[""] #邮件通知用户列表

[charges]
    [charges.CNY]
    coinId=1
    minActiveAllowed=5     #最低阈值
    rechargeAmount=100     #每次充值数量
    maxRechargeTimes=2     #每天最多充值次数

    [charges.BTC]
    coinId=2
    minActiveAllowed=100  
    rechargeAmount=1000        
    maxRechargeTimes=2

    [charges.BTY]
    coinId=3
    minActiveAllowed=100  
    rechargeAmount=1000        
    maxRechargeTimes=2

    [charges.ETH]
    coinId=4
    minActiveAllowed=100  
    rechargeAmount=1000        
    maxRechargeTimes=2

    [charges.ETC]
    coinId=5
    minActiveAllowed=100  
    rechargeAmount=1000        
    maxRechargeTimes=2

    [charges.SC]
    coinId=7
    minActiveAllowed=100  
    rechargeAmount=1000        
    maxRechargeTimes=2

    [charges.ZEC]
    coinId=8
    minActiveAllowed=100  
    rechargeAmount=1000        
    maxRechargeTimes=2

    [charges.BTS]
    coinId=9
    minActiveAllowed=100  
    rechargeAmount=1000        
    maxRechargeTimes=2

    [charges.LTC]
    coinId=10
    minActiveAllowed=100  
    rechargeAmount=1000        
    maxRechargeTimes=2

    [charges.BCC]
    coinId=11
    minActiveAllowed=100  
    rechargeAmount=1000        
    maxRechargeTimes=2

    [charges.USDT]
    coinId=15
    minActiveAllowed=100  
    rechargeAmount=1000        
    maxRechargeTimes=2

    [charges.DCR]
    coinId=17
    minActiveAllowed=100  
    rechargeAmount=1000        
    maxRechargeTimes=2